kind: Pod
apiVersion: v1
metadata:
      name: jenkinspod1
      namespace: tejsinghrana
      labels:
           adhoc: tejsinghranaq9
spec:
     containers:
           - image: jenkins
             name: jenkins
             ports:
                 - containerPort: 8080
             volumeMounts:
                   - name: jenkins-home
                     mountPath: /var/jenkins_home
     volumes:
          - name: jenkins-home
            hostPath:
                 path: jenkins-data
                 type: Directory
