apiVersion: v1
kind: Pod
metadata:
     name: adhocpod2
     namespace: tejsinghrana
     labels:
          adhoc: tejsinghranaq3
spec:
   containers:
         - image: flamebaba/may2020q1:v1
           name: minion2
           env:
              - name: x
                value: app2
                nodeName:     
           ports:
              - containerPort: 80
   nodeName: ip-172-31-36-77.ec2.internal 
---
apiVersion: v1
kind: Service
metadata:
     name: q3svctejsinghrana
     namespace: tejsinghrana
spec:
     type: NodePort
     ports:
        - port: 80
          targetPort: 80
          nodePort: 32565
     selector:
          adhoc: tejsinghranaq3
