apiVersion: v1
kind: Pod
metadata:
      name: adhocpod7
      namespace: tejsinghrana
      labels:
           adhoc: tejsinghranaq7
spec:
      containers:
            - image: alpine
              name: alpha
              command: ["/bin/sh","-c","while true ; do date >> /mnt/date.txt;sleep 3;done"]
              volumeMounts:
                    - name: local
                      mountPath: /mnt/
      restartPolicy: Always
      volumes:
           - name: local
             emptyDir: {}
