apiVersion: v1
kind: Pod
metadata:
      name: adhocpod7
      namespace: tejsinghrana
      labels:
           adhoc: tejsinghranaq7
spec:
      containers:
            - image: alpine
              name: alpha
              command:
                  - /bin/bash
                  - -c
                  - while true; do date >> /mnt/date.txt;sleep 3; done
              volumeMounts:
                    - name: local
                      mountPath: /mnt/date.txt
      volumes:
           - name: local
             hostPath:
                  path: /adhocoutput.txt
                  type: File
                  
