kind: Pod
apiVersion: v1
metadata:
      name: minion3
      namespace: tejsinghrana
      labels:
          adhoc: tejsinghranaq6
spec:
     containers:
             - image: portainer/portainer
               name: portainer
               ports:
                  - containerPort: 9000
               volumeMounts:
                   - name: pot
                     mountPath: /var/run/docker.sock
     volumes:
          - name: pot
            hostPath:
                  path: /var/run/docker.sock
                  type: Socket
     nodeName:  ip-172-31-41-104.ec2.internal             
---
kind: Service
apiVersion: v1
metadata:
      name: q6svctejsingrahan
      namespace: tejsinghrana
spec:
     type: NodePort
     ports:
           - port: 9000
             targetPort: 9000
     selector:
          adhoc: tejsinghranaq6


